Update issuer-web deployment configurations
bcgov/essential-services-delivery pull request #90
Opened 2020-12-21 22:18 UTC by esune

Resolves #89 

Deployments have been updated in all environments.

----

@swcurran if you want to add the help dialog for an issuer (after this PR i merged):
- update the `help.html` file for the profile the same way you have already done for the terms and conditions, adding your HTML content and styling.
- update `config.json` for that issuer, for each environment (`dev/test/prod`) and set help to `enabled: true`. This will turn the feature on and display a help icon in the navigation bar. If you also want the help dialog to automatically be displayed the first time a new user hits the credential data page for that website also set `displayOnFirstVisit: true`.

2020-12-22 14:43 UTC, WadeBarnes requested changes

2020-12-22 14:43 UTC, WadeBarnes commented on openshift/templates/issuer-web/issuer-web-deploy.esr2.prod.param
> +# APP_HELP_FILE_NAME=help.html
Duplicate line

2020-12-23 17:14 UTC, WadeBarnes approved these changes

2020-12-23 17:15 UTC, esune commented on openshift/templates/issuer-web/issuer-web-deploy.esr2.prod.param
> +# APP_HELP_FILE_NAME=help.html
oops!

2020-12-23 17:15 UTC, merged